sudo: 'required'

services:
  - 'docker'

env:
 global:
 - COMMIT=${TRAVIS_COMMIT::6}
 - IMAGE=ansible-docker-alpine

jobs:
  include:
    - stage: "Check docker image"
      script:
      - docker build -f Dockerfile -t $IMAGE:$COMMIT .
      if: type = pull_request
    - stage: "Build and Push Docker Image"
      script:
      - docker build -f Dockerfile -t $IMAGE:$COMMIT .
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker tag $IMAGE:$COMMIT $DOCKER_REPO/$IMAGE:$TAG
      - docker push $DOCKER_REPO/$IMAGE:$TAG
      if: type = push AND env(DOCKER_REPO) != "" AND env(DOCKER_USERNAME) != ""
      
