sudo: 'required'

services:
  - 'docker'

env:
 global:
 - COMMIT=${TRAVIS_COMMIT::6}
 - IMAGE=lagoonplatform/ansible-docker-alpine
 
script:
  - docker build -t $IMAGE:$COMMIT .

after_success:
  - export TAG=`if [ “$TRAVIS_BRANCH” == “master” ]; then echo “latest”; else echo $TRAVIS_BRANCH ; fi`
  - echo $IMAGE:$TAG:$COMMIT:$TRAVIS_EVENT_TYPE:$TRAVIS_PULL_REQUEST
#  - docker build -f Dockerfile -t $IMAGE:$COMMIT .
#  - docker tag $IMAGE:$COMMIT $IMAGE:$TAG
#  - docker push $IMAGE:$TAG